package net.redvoiss.sms.smpp;

import net.redvoiss.sms.smpp.bean.Message;

/**
 *
 * @author Jorge Avila
 */
public interface EsmeEventHandler {

    /**
     * Handles submit
     *
     * @param submitContext
     * @param sequenceNumber assigned during message creation
     * @param message message sent
     */
    public void handleSubmit(SubmitContext submitContext, Integer sequenceNumber, Message message);

    /**
     * Handles submit response
     *
     * @param sequenceNumber Sequence number. Should be the same than the one
     * the client used to
     * @param commandStatus Status
     * @param messageId Message id generated by server
     */
    public void handleSubmitResponse(Integer sequenceNumber, int commandStatus, String messageId);

    /**
     * Gets message id from header in deliver
     *
     * @param messageId message id from header
     * @param dlr message from deliver
     */
    public void handleDLR(String messageId, String dlr);

    /**
     * Gets message id from deliver message
     *
     * @param dlr message from deliver
     */
    public void handleDLR(String dlr);

    /**
     * Handles error for message
     *
     * @param submitContext
     * @param message
     */
    public void handleError(SubmitContext submitContext, Message message);

}
